# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findFirstGE <- function(x, target, forward = TRUE) {
    .Call('_TDEDice_findFirstGE', PACKAGE = 'TDEDice', x, target, forward)
}

