# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' findFirstGE
#'
#' Find the first index `i` in `x` for which `x[i] >= target` holds true.
#' @param x A numeric vector with monotonously increasing values.
#' @param target A numeric vector.
#' @details This is a helper function for quantile functions.
#' It also works outside the value range [0, 1], but has been tested
#' most extensively within this range.
#'
#' The comparison uses a precision of 1E-8.
#' @returns For each target it returns the first `x[i]` (from left to right)
#' for which `x[i] >= target` holds true.
#' If `target` is greater than any `x`, it returns `NA`.
findFirstGE <- function(x, target, forward = TRUE) {
    .Call('_TDEDice_findFirstGE', PACKAGE = 'TDEDice', x, target, forward)
}

